adding Museums project
Hello-Go-Hard/Museum_artefacts pull request #1
Opened 2020-02-03 11:01 UTC by Hello-Go-Hard

Museum artefacts project

2020-02-03 11:08 UTC, MaksimDanilau commented
`Museam_1.py`, `Museam_3.py` в названиях файлов ошибки правописания

2020-02-03 11:35 UTC, Hello-Go-Hard commented
а кроме этого?

2020-02-03 13:01 UTC, MaksimDanilau reviewed
В целом ты справился с заданием, но код нужно отрефакторить и доработать, чтобы я его принял.

Рекомендую делать задания на чистом питоне, без использования либ

Я бы реккомендовал эти задания выполнять на чистом питоне без

2020-02-03 13:01 UTC, MaksimDanilau commented on Museam_1.py
> +    output.to_csv('general-stats.csv')
Не вижу, где вызываются методы `a`, `b` и `c`. Неиспользуемого кода в исходниках быть не должно

2020-02-03 13:01 UTC, MaksimDanilau commented on Museam_1.py
> +    print(some_series)
`print` может использоваться для дебага при разработке, но в исходниках, опять же, его следует избегать

2020-02-03 13:01 UTC, MaksimDanilau commented on Museam_1.py
> +    print(
аналогично `print`

2020-02-03 13:01 UTC, MaksimDanilau commented on Museam_1.py
> +    print("Unknown weight ", count_of_nan)
аналогично `print`

2020-02-03 13:01 UTC, MaksimDanilau commented on Museam_1.py
> +    data = pd.read_csv('cstmc-CSV-en.csv', sep='|', error_bad_lines=False)
При запуске твоего скрипта в консоли достаточно много текста, в том числе там попадается такой
`Skipping line 8691: expected 36 fields, saw 38`

Как думаешь, что он значит?

2020-02-03 13:01 UTC, MaksimDanilau commented on Museam_1.py
> +        if str(some_series['NumberOfComponents'][i]) == 'nan':
Единственный верный способ проверить `numpy` число на `nan` это метод `isnan`. Всё остальное выдаст ложный результат.

Но с приведением к `str` выкрутился ты прикольно :smile:

2020-02-03 13:01 UTC, MaksimDanilau commented on Museam_1.py
> +    for i in some_series.index:
Внутри цикла много лишних действий.
`data[data['NumberOfComponents'].isna()].size` - тоже самое в одну строку

2020-02-03 13:01 UTC, MaksimDanilau commented on Museam_1.py
> +def d():
название метода должно отражать то, что он делает

2020-02-03 13:01 UTC, MaksimDanilau commented on Museam_1.py
> +    some_series = data[['ObjectName', 'NumberOfComponents']]
В результате ты получишь DataFrame, переменная должна называться соответсвующе

2020-02-03 13:01 UTC, MaksimDanilau commented on Museam_1.py
> +        some_series.loc[some_series['NumberOfComponents'].astype(float).idxmax()][['ObjectName', 'NumberOfComponents']])
Приведение к float избыточно, там и так тип numpy.float64

2020-02-03 13:01 UTC, MaksimDanilau commented on Museum_2.py
> +            continue
exception на то и искючительная ситуция, чтобы в крайнем случае её избежать

логика не должна работать на игнорировании ошибок

2020-02-03 13:01 UTC, MaksimDanilau commented on Museum_2.py
> +for i in ctgr:
```
from functools import reduce
result = reduce(lambda a, b: a.add(b, fill_value=0), ctgr)
```
В результате ты и получишь то, что искал

2020-02-05 10:52 UTC, MaksimDanilau commented on first_task.py
> +output.to_csv('general-stats.cvs')
Добавлять в проект _**pandas**_ только ради записи в файл нерационально.

Обрати внимание на пакет csv из STL. В частности на [csv.DictWriter](https://docs.python.org/3/library/csv.html#csv.DictWriter)

В расширении итогового файла ошибка: ~cvs~ csv - comma-separated values

2020-02-05 11:37 UTC, MaksimDanilau requested changes
Стало лучше. Надеюсь что и степень понимания увеличилась.

В стандартной поставке Python, помимо интерпритатора, есть куча полезных либ. В этом задании будет уместно заюзать пакет [csv](https://docs.python.org/3/library/csv.html).

Из задания в задание, ты парсишь один и тот же csv-файл. Поэтому было бы логично вынести отвечающий за это код в отделный файл и использовать его как библиотеку.

Думаю ещё одна-две итерации и будет хорошо

2020-02-05 11:37 UTC, MaksimDanilau commented on first_task.py
> +    some_artefact = i.split('|')
Ошибка в названии переменной, такое бросается в глаза _art~e~**i**fact_

2020-02-05 11:37 UTC, MaksimDanilau commented on first_task.py
> +        some_artefact =some_artefact[:-1]
`-1` в данном случае магическое число
если ты хочешь взять только первые 36 значений, то логичнее сделать `some_artifact[:36]`

2020-02-05 11:37 UTC, MaksimDanilau commented on first_task.py
> +country = structuring_data[column_name['ManuCountry']]
если переменная хранит множество значенией, то и название у неё должно быть в множественном числе
`countries`

2020-02-05 11:37 UTC, MaksimDanilau commented on first_task.py
> +for i in set_of_country:
название переменной `i` ни о чём не говорит

2020-02-05 11:37 UTC, MaksimDanilau commented on first_task.py
> +EndDate_list = structuring_data[column_name['EndDate']]
при написании кода лучше придерживаться определённого стиля

[PEP 8](https://www.python.org/dev/peps/pep-0008/#function-and-variable-names) - прекасно подойдёт

в данном случае название переменных не по конвеншену

2020-02-05 11:37 UTC, MaksimDanilau commented on first_task.py
> +file_csv = open("cstmc-CSV-en.csv", 'r')
Окей, файл открыли, а закрывать кто будет?

2020-02-06 07:57 UTC, MaksimDanilau requested changes

2020-02-06 07:57 UTC, MaksimDanilau commented on first_task.py
>      structuring_data.append(some_array)
Прочитай про [csv.DictReader](https://docs.python.org/3/library/csv.html#csv.DictReader) и попробуй переписать код с его использованием

2020-02-06 08:01 UTC, MaksimDanilau commented
> Из задания в задание, ты парсишь один и тот же csv-файл. Поэтому было бы логично вынести отвечающий за это код в отделный файл и использовать его как библиотеку.

@Hello-Go-Hard этот пункт не учёл

2020-02-06 08:05 UTC, MaksimDanilau requested changes
Описано выше

2020-02-17 13:48 UTC, closed without merging